### PR TITLE
GitHub issues with has-replay label

### PR DESCRIPTION
**Pull request by ceceliacreates**
Gets data from GitHub API and displays on a new /issues page.

Uses a GitHub access token in local .env, will need to set up GitHub secret to deploy. CSS is very messy, we may want to use tailwind or something instead. 

Wanted to get something for review though.

https://app.replay.io/recording/issues-page--11a15c65-12a3-4f55-a34f-875d3f998788

### CODE REVIEW

**Review by jasonLaster — APPROVED** [review]

**Comment by jasonLaster** [comment]
do we still need `data/issues.json` i could see the answer being yes for testing and offline mode, but want to check

**Comment by jasonLaster** [comment]
Looks like vercel failed for silly reasons

I think we should probably disable this lint stuff in builds `next.config.js`
```
  eslint: {
    ignoreDuringBuilds: true,
  },
```

Screen Shot 2022-04-28 at 9 58 01 AM

**Comment by ceceliacreates** [comment]
> do we still need `data/issues.json` i could see the answer being yes for testing and offline mode, but want to check

Exactly, I had it initially for testing before hooking up the live API, and could be used for that going forward as well. I should update it though so it matches the format expected by the front end, because I think it's a little different.

**Comment by ceceliacreates** [comment]
Just waiting to merge until we get the GitHub API key set up.

**Comment by ceceliacreates** [comment]
I'll actually need access to Vercel where the build step happens to set up the API key environment variable. Sorry I assumed this used GitHub Actions for some reason.

**Pull request merged**
